apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ssl
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-ssl
  template:
    metadata:
      labels:
        app: nginx-ssl
    spec:
      containers:
      - name: nginx
        image: replication-nginx:1.0
        ports:
        - containerPort: 443
        volumeMounts:
        - name: certs
          mountPath: /etc/certs
      volumes:
      - name: certs
        secret:
          secretName: ssl
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-ssl-service
spec:
  selector:
    app: nginx-ssl
  ports:
    - port: 443
---
# this is the nginx ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dictionary-nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx-ssl-service
            port:
              number: 443
---