version: '3'
services:
  nodeapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - APP_NAME=App1
    ports:
      - "3000:3000"
  
  nginxserver:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    environment:
      - APP_NAME=App2
    ports:
      - "443:443"