---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxied-legacy
spec:
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
        - name: legacyhello
          image: legacyhello:1.0
          ports:
            - containerPort: 3000
        - name: nginx
          image: nginx-ssl-proxy:1.0
          ports:
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: proxied-service
spec:
  selector:
    app: my-nginx
  ports:
    - port: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: proxied-service
            port:
              number: 443
---